name: Super Tux Animation Generator

permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 * * *" # daily at midnight UTC
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Setup Python (or any required env)
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install pillow  # example if you use Python to create GIFs

      - name: Generate Super Tux Animation GIF
        run: |
          # This is where you run your script to generate the GIF
          # Example placeholder:
          ./scripts/generate-supertux-gif.sh dist/supertux.gif

      - name: Deploy to Output Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          commit_message: "Update Super Tux animation [skip ci]"

