name: Atualizar GIF Diário

on:
  schedule:
    - cron: '0 0 * * *'  # Todos os dias à meia-noite UTC
  workflow_dispatch:  # Para correr manualmente também

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Instalar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Instalar dependências
      run: npm install

    - name: Gerar GIF atualizado
      run: node generate-super-tux-snake.js  # substitui pelo teu script exato que gera o gif
    
    - name: Commit e Push dos GIFs atualizados
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add super-tux-snowy-questions.gif super-tux-game-effect.gif  # ou os ficheiros que forem
        git commit -m "Atualização diária do GIF"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
